apps/love/mobile/controllers/FaveController.php
<?php

class FaveController extends MobileController
{
	public function accessRules()
	{
		return array(
			array('deny',
			      //'actions'=>array('index'),
			      'users'=>array('?'),
			),
		);
	}
	
	public function actionIndex()
	{
		/*if (Yii::app()->request->isAjaxRequest)
		{
			$this->layout=false;
			$criteria=new CDbCriteria;
		
			$criteria=new CDbCriteria(array(
				'condition'=>'`fave`.`userId`=:userId',
				'params'=>array(':userId'=>Yii::app()->user->id),
				'order'=>'fave.time DESC',
				'with'=>'fave',
			));
			
			$count = Photos::model()->count($criteria);
			$pages = new CPagination($count);
			$pages->pageSize=Yii::app()->params['favePhotos_limit'];
			$pages->applyLimit($criteria);
			
			$photos=Photos::model()->findAll($criteria);
			foreach ($photos as $key=>$row) {
				
				$p = new stdClass();
				$p->id=$row->id;
				$p->user_id=$row->user_id;
				$p->filename=$row->filename;
				$p->descr=$row->descr;
				$p->width=$row->width;
				$p->height=$row->height;
				$p->likes=$row->likes;
				$p->date=Html::date($row->date);
				$p->image=$row->imageSource;
				$p->commentsUrl=CHtml::normalizeUrl(array('photos/comments', 'id'=>$row->id));
				$p->likeUrl=CHtml::normalizeUrl(array('photos/like', 'id'=>$row->id));
				$photos_all[]=$p;
			}
			
			foreach ($photos as $key=>$row) {
				$nums[$row->id]=array('key'=>$key);
			}
		
			echo CJSON::encode(array(
				'photoId' => Yii::app()->request->getQuery('photoId'),
				'photos' => $photos_all,
				'nums' => $nums,
				'count' => $count,
				'limit' => $pages->pageSize,
			));
			Yii::app()->end();
		}*/
		
		$criteria=new CDbCriteria(array(
			'condition'=>'`fave`.`userId`=:userId',
			'params'=>array(':userId'=>Yii::app()->user->id),
			'order'=>'fave.time DESC',
			'with'=>'fave',
		));
		
		$count = Like::model()->count('`t`.`userId`=:userId', array(':userId'=>Yii::app()->user->id));
		$pages = new CPagination($count);
		$pages->pageSize=Yii::app()->params['favePhotos_limit'];
		$pages->applyLimit($criteria);
			//echo $pages->PageCount;
		$photos=Photos::model()->with('user')->findAll($criteria);
		
		$this->render('index',array('photos'=>$photos, 'pages'=>$pages));
		
	}
	
	public function actionUsers()
	{
		$criteria=new CDbCriteria(array(
			'condition'=>'fave.userId=:userId',
			'params'=>array(':userId'=>Yii::app()->user->id),
		));
		$count = UserLikes::model()->count('t.userId=:userId', array(':userId'=>Yii::app()->user->id));
		
		$pages = new CPagination($count);
		$pages->pageSize=Yii::app()->params['faveUsers_limit'];
		$pages->applyLimit($criteria);
		
		$users=User::model()->with('city')->with('fave')->findAll($criteria);
		
		$this->render('users',array('users'=>$users, 'pages'=>$pages));
	}
}

apps/love/mobile/controllers/MessagesController.php
<?php

class MessagesController extends MobileController
{
	public $layout='col_main';
	
	public function accessRules()
	{
		return array(
			array('deny',
			      'actions'=>array('index', 'dialogue'),
			      'roles'=>array('guest'),
			),
		);
	}
	
	public function actionIndex()
	{
		if (Yii::app()->request->isPostRequest && is_array($_POST['to_message']))
		{
			foreach($_POST['to_message'] as $item) {
				Messages::model()->deleteByPk($item, 'from_userId='.Yii::app()->user->id);
			}
			
			if (Yii::app()->request->isAjaxRequest) {
				echo CJSON::encode(array());
				return;
			}
		}
		
		$criteria=new CDbCriteria(array(
			'condition'=>'`t`.`from_userId`=:user_id AND `t`.`folder`=:folder',
			'params'=>array(':user_id'=>Yii::app()->user->id, ':folder'=>$_GET['folder']=='outbox' ? 'outbox' : 'inbox'),
			'with'=>array('user'=>array()),
			'order'=>'t.time DESC',
				
		));
		
		$count = Messages::model()->count($criteria);
		$pages = new CPagination($count);
		$pages->pageSize=Yii::app()->params['messages_limit'];
		$pages->applyLimit($criteria);
		
		$messages=Messages::model()->findAll($criteria);
		
		if (Yii::app()->request->isAjaxRequest && $_GET['_a']=='container_mail') {
			$this->render('_index', array('messages'=>$messages, 'pages'=>$pages, 'count'=>$count));
		} else {
			$this->render('index', array('messages'=>$messages, 'pages'=>$pages, 'count'=>$count));
		}
	}
	
	public function actionDialogue()
	{
		if (Yii::app()->request->isPostRequest && is_array($_POST['to_message']))
		{
			foreach($_POST['to_message'] as $item) {
				Messages::model()->deleteByPk($item, 'from_userId='.Yii::app()->user->id);
			}
			
			if (Yii::app()->request->isAjaxRequest) {
				echo CJSON::encode(array());
				return;
			}
		}
		
		$user=User::model()->findByPk($_GET['id']);
		
		if($user===null)
			throw new CHttpException(404,'Contact not found.');
		
		if($user->id==Yii::app()->user->id)
			throw new CHttpException(404,'It is impossible to write a message.');
		
		
		$model=new Messages;
		
		if(Yii::app()->request->isPostRequest && !Yii::app()->user->isGuest)
		{
			$model->attributes=$_POST['Messages'];
			if($model->validate())
			{
				$model->from_userId = $user->id;
				$model->to_userId = Yii::app()->user->id;
				$model->unread = 1;
				$model->folder = 'inbox';
				$model->time = time();
				
				if ($model->save(false))
				{
					$model=new Messages;
					$model->attributes=$_POST['Messages'];
					$model->from_userId = Yii::app()->user->id;
					$model->to_userId = $user->id;
					$model->folder = 'outbox';
					$model->unread = 0;
					$model->time = time();
					if ($model->save())
					{
						if (Yii::app()->request->isAjaxRequest)
						{
							echo CJSON::encode(array('html'=>$this->getDialogue($_GET['id'])));
							return;
						}
						Yii::app()->user->setFlash('sent','to');
						$this->refresh();
					}
				}
			}
			elseif (Yii::app()->request->isAjaxRequest)
			{
				echo CActiveForm::validate($model);
				Yii::app()->end();
			}
		}
		
		if (Yii::app()->request->isAjaxRequest && $_GET['_a']=='container_mail') {
			echo $this->getDialogue($user->id);
		} else {
			$this->render('dialogue', array('user'=>$user, 'model'=>$model));
		}
	}
	
	public function getDialogue($id)
	{
		$criteria=new CDbCriteria(array(
			'condition'=>'`t`.`from_userId`=:user_id AND `t`.`to_userId`=:to_userId',
			'params'=>array(':user_id'=>Yii::app()->user->id, ':to_userId'=>$id),
			'with'=>array('user'=>array()),
			'order'=>'t.time DESC',
				
		));
		
		$count = Messages::model()->count($criteria);
		$pages = new CPagination($count);
		$pages->pageSize=Yii::app()->params['messages_limit'];
		$pages->applyLimit($criteria);
		
		$messages=Messages::model()->findAll($criteria);
		
		foreach($messages as $row) {
			if ($row->unread)
				$row->saveAttributes(array('unread'=>0));
		}

		return $this->renderPartial('_dialogue', array(
			'messages'=>$messages,
			'pages'=>$pages,
			'count'=>$count)
		, true);
	}
	
	public function actionSend()
	{
		$user=User::model()->findByPk($_GET['id']);
		
		if($user===null)
			throw new CHttpException(404,'Contact not found.');
		
		if($user->id==Yii::app()->user->id)
			throw new CHttpException(404,'It is impossible to write a message.');
		
		$model=new Messages;
		
		if(Yii::app()->request->isPostRequest && !Yii::app()->user->isGuest)
		{
			$model->attributes=$_POST['Messages'];
			if($model->validate())
			{
				
				$model->from_userId = $user->id;
				$model->to_userId = Yii::app()->user->id;
				$model->unread = 1;
				$model->folder = 'inbox';
				$model->time = time();
				
				if ($model->save(false))
				{
					$model=new Messages;
					$model->attributes=$_POST['Messages'];
					$model->from_userId = Yii::app()->user->id;
					$model->to_userId = $user->id;
					$model->folder = 'outbox';
					$model->unread = 0;
					$model->time = time();
					if ($model->save())
					{
						if (Yii::app()->request->isAjaxRequest)
						{
							echo CJSON::encode(array('ok'=>1));
							Yii::app()->end();
						}
						Yii::app()->user->setFlash('sent','to');
						$this->refresh();
					}
				}
			}
			elseif (Yii::app()->request->isAjaxRequest)
			{
				echo CActiveForm::validate($model);
				Yii::app()->end();
			}
		}
		
		$this->render('send', array('model'=>$model, 'user'=>$user));
	}
}

apps/love/mobile/views/fave/_menu.php
<div class="mytabs" style="margin-top:-15px;">
<?php $this->widget('Menu', array(
	'htmlOptions'=>array('class'=>'nav nav-tabs nav-friends'),
    'encodeLabel'=>false,
			'items'=>array(
				array('label'=>'Фотографии', 'url'=>array('fave/index'), 'linkOptions'=>array()),
				array('label'=>'Люди', 'url'=>array('fave/users'), 'linkOptions'=>array()),
			),
)); ?>
</div>

apps/love/mobile/views/fave/_photos.php
<?php if (!$photos): ?>
<p class="text-muted text-center">Закладки пусты.</p>
<?php endif;?>
<div class="row profile-photos">
		<?php foreach($photos as $key=>$row): $params=[]; if (isset($_GET['albumId'])) $params['albumId']=$_GET['albumId'];?>
		<div id="i<?=$row->id; ?>" class="col-md-2 col-xs-3 col-sm-2 profile-photos-row ">
		<a href="<?=CHtml::normalizeUrl(array_merge(array('photos/show', 'userId'=>$row->user_id, 'photoId'=>$row->id), $params));; ?>"><img src="<?php echo ImageHelper::thumb(130, 100, $row->user_id, $row->filename, array('method' => 'adaptiveResize'));?>" class="img-responsive" border="0" /></a>
		
		</div>
		<?php endforeach; ?>
</div>

<div class="text-center">
<?php $this->widget('ext.bootstrap3.widgets.BsPager', array(
        //'id'=>'wallPages',
        'pages'=>$pages,
       // 'cssFile'=>Html::cssUrl('pager.css'),
	'htmlOptions'=>array('class'=>'pagination pagination-sm'),
        //'maxButtonCount'=>5,
        'nextPageLabel'=>'<i class="fa fa-angle-right"></i>',
	'prevPageLabel'=>'<i class="fa fa-angle-left"></i>',
        'lastPageLabel'=>'<i class="fa fa-angle-double-right"></i>',
	'firstPageLabel'=>'<i class="fa fa-angle-double-left"></i>',
        ));
?>
</div>

apps/love/mobile/views/fave/index.php
<?php
$this->pageTitle='Мои закладки';
$this->breadcrumbs=array(
	'Мои закладки'
);
?>
            <div class="title row">
                <div class="col-md-12 col-xs-12">
                    <h3 class="pull-left">Мои закладки</h3>
                </div>   
            </div>
<?php $this->renderPartial('_menu', array()); ?>

<div class="photos-list" id="fPhotos">
<?php $this->renderPartial('_photos', array('photos'=>$photos)); ?>
</div>

apps/love/mobile/views/fave/users.php
<?php
$this->pageTitle='Мои закладки';
$this->breadcrumbs=array(
	'Мои закладки'
);
?>
            <div class="title row">
                <div class="col-md-12 col-xs-12">
                    <h3 class="pull-left">Мои закладки</h3>
                </div>   
            </div>
<?php $this->renderPartial('_menu', array()); ?>
<?php if (!$users): ?>
<p class="text-muted text-center">Закладки пусты.</p>
<?php endif;?>
<div class="row dialogue">
<div class="recording-wall b-notice" style="margin-left:0px;margin-right:0px;">
<?php foreach($users as $num=>$row):?>
                <?php if ($num>0):?><hr style="margin-top:5px;margin-bottom:10px;"/><?php endif;?>
		
                <div class="row" id="comment_<?=$row->id?>" style="margin-right:0px;">
                    <div class="col-xs-3 col-sm-2 col-md-2 text-left" style="width:80px;">
<?php
if ($row->id):
	echo CHtml::link(
		CHtml::image( 
			$row->getImage(55,55, 'camera_s.png'),
			'',
			array('class'=>'ava')
		), 
		$row->url,
		array()
	);
else:
	echo CHtml::image( 
			Html::imageUrl('camera_s.png'),
			'',
			array('class'=>'ava')
		);
endif;
?>
                    </div>
                    <div class="col-xs-8 col-sm-10 col-md-10">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="notice-text">
                                    <div class="head"><?php
	echo CHtml::link(
		$row->name ? $row->name : DELETED, 
		$row->url,
		array('rel'=>'ajax1')
	);
?>
<?php if ($row->isOnline):?>
								<label class="dialogue-online"><?php if (!$row->isMobile):?><i class="fa fa-circle"></i><?php else:?><i class="fa fa-mobile"></i>Mobile<?php endif;?></label>
<?php endif;?>
				    </div>
				    <div class="menu-wall clearfix">
		<?php $this->widget('Menu',array(
			//'type'=>'list',
			'htmlOptions'=>array('class'=>'friend-nav'),
			'encodeLabel'=>false,
			'hideEmptyItems'=>false,
			'firstItemCssClass'=>'first',
			'lastItemCssClass'=>'last',
			'items'=>array(
				array('label'=>'<i class="fa fa-envelope"></i>Написать сообщение', 'url'=>array('messages/dialogue', 'id'=>$row->id), 'linkOptions'=>array('id'=>'showModalSendMessage')),
				array('label'=>'<i class="fa fa-camera"></i>Смотеть фотографии', 'url'=>array('photos/show', 'userId'=>$row->id, 'albumId'=>0, 'photoId'=>$row->photoId), 'linkOptions'=>array('id'=>'showModalPhotoBox')),
			),
		)); ?>
				    </div>
				    <div class="message"></div>

                                </div> 
                            </div>     
                        </div>
                    </div>
                </div> 
<?php endforeach; ?>
</div>

<div class="text-center">
<?php $this->widget('ext.bootstrap3.widgets.BsPager', array(
        //'id'=>'wallPages',
        'pages'=>$pages,
       // 'cssFile'=>Html::cssUrl('pager.css'),
	'htmlOptions'=>array('class'=>'pagination pagination-sm'),
        //'maxButtonCount'=>5,
        'nextPageLabel'=>'<i class="fa fa-angle-right"></i>',
	'prevPageLabel'=>'<i class="fa fa-angle-left"></i>',
        'lastPageLabel'=>'<i class="fa fa-angle-double-right"></i>',
	'firstPageLabel'=>'<i class="fa fa-angle-double-left"></i>',
        ));
?>
</div>
</div>