apps/love/mobile/controllers/ActivationController.php
<?php
Yii::import('vc.components.VCActivationController');

class ActivationController extends VCActivationController
{
	public $pageTitle;
	public $layout='col_main';
	
	public function filters()
	{
		return array(
			//'accessControl',
			array(
				'AccessControlFilter',
				'rules'=>$this->accessRules(),
			)
		);
	}
	
	public function accessRules()
	{
		return array(
			array('deny',
			      'roles'=>array('guest'),
			),
		);
	}
	
	/*public function actions()
	{
		return array(   
			'handler' => 'vc.actions.VCActivationAction'   
		);   
	}*/
	
	public function actionIndex()
	{
		$country=VC_BillCountry::model()->findByAttributes(array('code'=>Yii::app()->vc->countryCode, 'status'=>'1'));
		if (empty($country->id)) {
			
			$this->actionBk();
			Yii::app()->end();
		}
		$this->render('index', array());
	}
	
	public function actionBk()
	{
				$kassa=new Kassa;
				$kassa->user_id=Yii::app()->user->id;
				$kassa->coins=20;
				$kassa->sum=$sum = Yii::app()->vc->subaccount->mc_tarif;
				$kassa->pay_status=0;
				$kassa->date=time();
				$kassa->save();
				
				
// Исходные данные
$shop_id = '11824';		// ID-магазинаы
$pass = '712cf92d6fe26aa10da8e0547de95863';			// Пароль магазина
$secret = 'c814dd85265b778fe3fc122c1b2e3202';		// Секретный ключ
$order = $kassa->id;		// Номер счета
$currency = 'RUR';		// RUR, USD, EUR, UAH
$sum = Yii::app()->vc->subaccount->mc_tarif;			// Сумма счета
//$sum = 50;			// Сумма счета
$prop = array(
	      Yii::app()->user->model->name,
	      Yii::app()->user->auth->email,
	      $kassaForm->phone
	      );	// Доп свойства

// Подготовка пакета $xml
$xml = "
<request>
	<order>$order</order>
	<shop>$shop_id</shop>
	<pass>$pass</pass>
	<sum>$sum</sum>
	<currency>$currency</currency>
	<property>
		<p0>$prop[0]</p0>
		<p1>$prop[1]</p1>
		<p2>$prop[2]</p2>
		<p3>$prop[3]</p3>
		<p4>$prop[4]</p4>
		<p5>$prop[5]</p5>
		<p6>$prop[6]</p6>
		<p7>$prop[7]</p7>
		<p8>$prop[8]</p8>
		<p9>$prop[9]</p9>
	</property>
</request>";
//echo $xml;
// Кодирование пакета $xml методом base64_encod
$xml_encoded = base64_encode($xml);
// Создание подписи
$lqsignature = base64_encode(sha1($secret.$xml_encoded.$secret,1));
				
		
		$this->render('bk', array('xml_encoded'=>$xml_encoded, 'lqsignature'=>$lqsignature));
	}
	
	
	public function activatedPseudo($how_many_sms=3) {
		parent::activated();
		$t=new Transaction();
		$t->coins=5;
		$t->user_id = Yii::app()->user->id;
		$t->comment_payment='Пополнение баланса через смс.';
		$t->save();
		
		$c=Transaction::model()->count('user_id='.Yii::app()->user->id);
		Yii::app()->user->model->saveAttributes(array('balance'=>new CDbExpression('`balance`+5')));
		
		if ($how_many_sms<=1) {
			return 'Ответьте на смс, чтобы получить на счет 5 монет и активировать Real-статус.';
		} elseif ($how_many_sms<=2) {
			return 'Ответьте на смс, чтобы активировать функцию отправки сообщений со своей анкеты другим участникам.';
		} else {
			Yii::app()->user->model->saveAttributes(array('isReal'=>1));
			return 'Real-статус активирован.';
		}
	}
	
	public function activatedSms($how_many_sms=3) {
		parent::activated();
		$t=new Transaction();
		$t->coins=5;
		$t->user_id = Yii::app()->user->id;
		$t->comment_payment='Пополнение баланса через смс.';
		$t->save();
		
		$c=Transaction::model()->count('user_id='.Yii::app()->user->id);
		Yii::app()->user->model->saveAttributes(array('balance'=>new CDbExpression('`balance`+5')));
		
		if ($c<=1) {
			return 'Вам требуется отправить второе смс-сообщение со своего мобильного телефона, чтобы получить на счет 5 монет и активировать Real-статус.';
		} elseif ($c<=2) {
			return 'Вам требуется отправить последнее смс-сообщение со своего мобильного телефона, чтобы активировать функцию отправки сообщений со своей анкеты другим участникам.';
		} else {
			Yii::app()->user->model->saveAttributes(array('isReal'=>1));
			return 'Real-статус активирован.';
		}
	}
	public function activatedMc() {
		parent::activated();
		$t=new Transaction();
		$t->coins=20;
		$t->user_id = Yii::app()->user->id;
		$t->comment_payment='Пополнение баланса через мобильный платеж.';
		$t->save();
		
		$c=Transaction::model()->count('user_id='.Yii::app()->user->id);
		Yii::app()->user->model->saveAttributes(array('balance'=>new CDbExpression('`balance`+20')));
		Yii::app()->user->model->saveAttributes(array('isReal'=>1));
		return 'Real-статус активирован.';
		
	}
}

apps/love/mobile/controllers/SettingsController.php
<?php

class SettingsController extends MobileController
{
	public $layout='col_main';
	
	public function accessRules()
	{
		return array(
			array('deny',
			      'roles'=>array('userNoActivated', 'guest'),
			),
		);
	}
	
	public function actionIndex()
	{
		$model=User::model()->findByPk(Yii::app()->user->id);
		
		$this->pageTitle='Настройки';
		$this->breadcrumbs=array(
			'Настройки',
		);
		
		$model->setScenario('edit');
		if(Yii::app()->request->isPostRequest)
		{
			$model->attributes=$_POST['User'];
			
			if($model->validate())
			{
				if ($model->save()) {
					Yii::app()->user->setFlash('edit','Изменения сохранены.');
					$this->refresh();
				}
			}
		}
		

		
		$this->render('index', array('model'=>$model));
	}
	
	public function actionPassword()
	{
		$this->pageTitle='Смена пароля';
		
		$this->breadcrumbs=array(
			'Настройки',
			'Смена пароля',
		);
		
		$user=UserAuthorization::model()->findByPk(Yii::app()->user->id);
		$user->setScenario('editPassword');
		$this->performAjaxValidation($user);
		if(Yii::app()->request->isPostRequest)
		{
			$user->attributes=$_POST['UserAuthorization'];
			if ($user->validate())
			{
				$user->password = $user->new_password;
				$user->hash_password = UserAuthorization::hashPassword($user->new_password);
				
				if ($user->save(false)) {
					if (Yii::app()->request->isAjaxRequest) {
						echo CJSON::encode(array('ok'=>'1'));
						return;
					} else {
						Yii::app()->user->setFlash('edit','Изменения сохранены.');
						$this->refresh();
					}
				}
			} elseif (Yii::app()->request->isAjaxRequest) {
				echo CActiveForm::validate($user);
				Yii::app()->end();
			}
		}
		$this->render('password', array('model'=>$user));
	}
	
	public function actionLogin()
	{
		$this->pageTitle='Смена логина';
		
		$this->breadcrumbs=array(
			'Настройки'=>array('settings/index'),
			'Смена логина',
		);
		
		$user=User::model()->findByPk(Yii::app()->user->id);
		$userPages=UserPages::model()->findByPk(Yii::app()->user->id);
		$user->setScenario('editLogin');
		$this->performAjaxValidation($user);
		if(Yii::app()->request->isPostRequest)
		{
			$user->attributes=$_POST['User'];
			if ($user->validate())
			{
				if ($user->save(false)) {
					$userPages->name=$user->login;
					$userPages->save();
					
					if (Yii::app()->request->isAjaxRequest) {
						echo CJSON::encode(array('ok'=>'1'));
						return;
					} else {
						Yii::app()->user->setFlash('edit','Изменения сохранены.');
						$this->refresh();
					}
				}
			} elseif (Yii::app()->request->isAjaxRequest) {
				echo CActiveForm::validate($user);
				Yii::app()->end();
			}
		}
		$this->render('login', array('model'=>$user));
	}
	
	public function actionEmail()
	{
		$this->pageTitle='Смена email';
		
		$this->breadcrumbs=array(
			'Настройки'=>array('settings/index'),
			'Смена email',
		);
		
		$user=UserAuthorization::model()->findByPk(Yii::app()->user->id);
		$user->setScenario('editEmail');
		$this->performAjaxValidation($user);
		if(Yii::app()->request->isPostRequest)
		{
			$user->attributes=$_POST['UserAuthorization'];
			if ($user->validate())
			{
				if ($user->save(false)) {

					if (Yii::app()->request->isAjaxRequest) {
						echo CJSON::encode(array('ok'=>'1'));
						return;
					} else {
						Yii::app()->user->setFlash('edit','Изменения сохранены.');
						$this->refresh();
					}
				}
			} elseif (Yii::app()->request->isAjaxRequest) {
				echo CActiveForm::validate($user);
				Yii::app()->end();
			}
		}
		$this->render('email', array('model'=>$user));
	}
	
	public function actionPhone()
	{
		$this->pageTitle='Смена телефона';
		
		$this->breadcrumbs=array(
			'Настройки'=>array('settings/index'),
			'Смена телефона',
		);
		
		$user=UserAuthorization::model()->findByPk(Yii::app()->user->id);
		$user->setScenario('editPhone');
		$this->performAjaxValidation($user);
		if(Yii::app()->request->isPostRequest)
		{
			$user->attributes=$_POST['UserAuthorization'];
			if ($user->validate())
			{
				if ($user->save(false)) {
					
					if (Yii::app()->request->isAjaxRequest) {
						echo CJSON::encode(array('ok'=>'1'));
						return;
					} else {
						Yii::app()->user->setFlash('edit','Изменения сохранены.');
						$this->refresh();
					}
				}
			} elseif (Yii::app()->request->isAjaxRequest) {
				echo CActiveForm::validate($user);
				Yii::app()->end();
			}
		}
		$this->render('phone', array('model'=>$user));
	}
	
	public function actionPrivacy()
	{
		$userSettings=UserSettings::model()->findByPk(Yii::app()->user->id);
		$this->performAjaxValidation($userSettings);
		if(Yii::app()->request->isPostRequest)
		{
			$userSettings->attributes=$_POST['UserSettings'];
			if ($userSettings->validate())
			{
				if ($userSettings->save(false)) {
					
					if (Yii::app()->request->isAjaxRequest) {
						echo CJSON::encode(array('ok'=>'1'));
						return;
					} else {
						Yii::app()->user->setFlash('edit','Изменения сохранены.');
						$this->refresh();
					}
				}
			} else {
				echo CActiveForm::validate($userSettings);
				Yii::app()->end();
			}
		}
		
		$this->render('privacy', array('model'=>$userSettings));
	}
	
	public function actionRemove()
	{
		
		//$themes=Themes::model()->findAll();
		
		$this->render('remove', array('users'=>$users));
	}
	
	public function actionBlacklist()
	{
		if (Yii::app()->request->isAjaxRequest && $_GET['bId'] && $_GET['bId']!=Yii::app()->user->id) {
			
			$b=Blacklist::checkBlackByUser($_GET['bId']);
			if ($b->id) {
				$b->delete();
				if (Yii::app()->request->isAjaxRequest) {
					echo CJSON::encode(array('status'=>'re_block', 'id'=>$_GET['bId']));
					Yii::app()->end();
				} else {
					//$this->refresh();
				}
			} else {
				$b=new Blacklist;
				$b->userId=Yii::app()->user->id;
				$b->black_userId=$_GET['bId'];
				$b->save();
				if (Yii::app()->request->isAjaxRequest) {
					echo CJSON::encode(array('status'=>'block', 'id'=>$_GET['bId']));
					Yii::app()->end();
				} else {
					//$this->refresh();
				}
			}
			
		}
		
		$criteria=new CDbCriteria(array(
			'condition'=>'`blacklist`.`userId`=:userId',
			'params'=>array(':userId'=>Yii::app()->user->id),
			'with'=>'blacklist',
		));
		$users=User::model()->findAll($criteria);
		
		$this->render('blacklist', array('users'=>$users));
	}
	
	public function actionThemes()
	{
		$model=User::model()->findByPk(Yii::app()->user->id);
		
		$this->pageTitle='Настройки дизайна страницы';
		$this->breadcrumbs=array(
			'Настройки дизайна страницы',
		);
		
		if($_GET['set'])
		{
			$theme=Themes::model()->findByPk($_GET['set']);
			//if ($theme->name)
				$model->saveAttributes(array('theme'=>$theme->name));
				
			$this->redirect(array('profile/index', 'user'=>Yii::app()->user->model->login));
		}
		
		$themes=Themes::model()->findAll();
		
		$this->render('themes', array('model'=>$model, 'themes'=>$themes));
	}
	
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='registerForm')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

apps/love/mobile/controllers/UserController.php
<?php

class UserController extends MobileController
{
	public $layout = 'col_main';
	

	
	public function actions()
	{
		return array(
                    //  captcha.
                     'captcha'=>array(
                        'class'=>'CaptchaAction',
                        'maxLength'=> 3,
                        'minLength'=> 4,
                        'testLimit'=> 1,
                    )
                );
	}
	
	public function actionIndex()
	{
		$this->actionLogin();
	}
	
	public function actionRegister()
	{
		if (!Yii::app()->user->isGuest)
			$this->redirect(Yii::app()->user->returnUrl);
			
		$user=new User;
		$user->setScenario('register');
		$this->performAjaxValidation($user);
		if(Yii::app()->request->isPostRequest)
		{
			$user->attributes=$_POST['User'];
			if($user->validate())
			{
				Yii::app()->vc->processStatField(array('reg'=>1));
				$user->subaccount_id=Yii::app()->vc->subaccountId;
				if ($user->save(false))
				{
					$auth=new LoginForm;
					$auth->username=$_POST['User']['email'];
					$auth->password=$_POST['User']['password'];
					$auth->rememberMe=true;
					$auth->login();
					$this->redirect(array('site/index'));
				}
			}
		}
		$this->render('register', array('model'=>$user));
	}
	
	public function actionLostpassword()
	{
		if (!Yii::app()->user->isGuest)
			$this->redirect(Yii::app()->user->returnUrl);
			
		$model=new LostpasswordForm;
		$user=false;
		if(Yii::app()->request->isPostRequest)
		{
			$model->attributes=$_POST['LostpasswordForm'];
			if($model->validate())
			{
				$userAuth = UserAuthorization::model()->find('email=:email', array(':email'=>$model->attributes['email']));
				$user = User::model()->findByPk($userAuth->user_id);
				if ($user->id)
				{
					$mail=Yii::app()->Smtpmail;
					$mail->CharSet='utf-8';
					$mail->SetFrom($mail->Username, Yii::app()->request->domain);
					$mail->Subject    = 'Восстановление пароля к '.Yii::app()->request->domain;
					$mail->MsgHTML($this->render('/email/lostpassword', array('email'=>$userAuth->email, 'password'=>$userAuth->password, 'name'=>$user->name), true));
					$mail->AddAddress($userAuth->email, "");
					if(!$mail->Send()) {
						throw new CHttpException(500,'Mailer Error.');
						//$model->addError('email', 'Mailer Error: ' . $mail->ErrorInfo);
					}else {
						Yii::app()->user->setFlash('sentemail',$userAuth->email);
						$this->refresh();
					}
				}
				else
					$model->addError('email', 'A user with this email was not found');
			}
		}
		
		$this->render('lostpassword', array('model'=>$model, 'user'=>$user));
	}
	
	public function actionLogin()
	{
		if (!Yii::app()->user->isGuest)
			$this->redirect(Yii::app()->user->returnUrl);
			
		if (isset($_GET['auto']))
		{
			$auto=explode(";", base64_decode($_GET['auto']));
			$auth=new LoginForm;
			$auth->username=$auto['0'];
			$auth->password=$auto['1'];
			$auth->rememberMe=true;
			$auth->login();
			$this->redirect(array('site/index'));
			Yii::app()->end();
		}
			
		$model=new LoginForm;
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			
			if($model->validate() && $model->login())
			{
				$this->redirect(array('site/index'));
			}
		}
		
		$this->render('login', array('model'=>$model));
	}
	
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='registerForm')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

apps/love/mobile/views/photos/_albumForm.php
<?php if(Yii::app()->user->hasFlash('edit')): ?>
<div class="alert alert-success">
	<?php echo Yii::app()->user->getFlash('edit'); ?>
</div>
<?php endif; ?>




<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'registerForm',
    'htmlOptions'=>array('class'=>'reg-form'),
    'enableClientValidation'=>true,
    'enableAjaxValidation'=>true,
    'clientOptions'=>array(
            'validateOnSubmit'=>true,
            'validateOnType'=>false,
            'validateOnChange'=>false,
            'beforeValidate'=>'js:function(){

                return true;
             }',
           'afterValidate' => 'js: function(form, data, hasError) {
if (!hasError) {
        $.ajax({
          type: "POST",
          url: $("#registerForm").attr("action"),
          data: $("#registerForm").serialize(),
	  dataType: "json",
	beforeSend: function(){
	$("#registerForm .btn").attr("disabled","disabled").fadeTo(1, 0.4);
			$("#loading_stat").show();
		},
          success: function(data){
	  if (data.redirect) {
	  location= data.redirect;
	  
	  return;
	  }
	  
	  
	  $("#loading_stat").hide();
	  $(".flash-success").fadeTo(\'speed\', 1.0);
	  

	  $("#registerForm .btn").removeAttr("disabled").fadeTo("speed", 1.0);
	  setTimeout("$(\'.flash-success\').fadeTo(\'speed\', 0.4);", 1500);

	  }

        });
        return false;
        }}'
            //'afterValidate'=>'js:afterValidateSettingsForm',
    ),

)); ?>
<?php echo CHtml::errorSummary($model);?>
<div class="alert alert-success flash-success" style="display:none;">
	Изменения сохранены.
</div>
						<div class="inputs">
<?php echo $form->labelEx($model,'name',array('class'=>'control-label')); ?>
		<?php echo $form->textField($model, 'name',array('class'=>'txt-field')); ?>
		<?php echo $form->error($model,'name'); ?>
						</div>	
						<div class="inputs">
<?php echo $form->labelEx($model,'descr',array('class'=>'control-label')); ?>
		<?php echo $form->textArea($model, 'descr',array('class'=>'textarea', 'style'=>'width:295px;')); ?>
		<?php echo $form->error($model,'descr'); ?>
						</div>	
						<div class="inputs">
<?php echo $form->labelEx($model,'access_to_view',array('class'=>'col-lg-3 control-label')); ?>

		<?php echo $form->dropDownList($model, 'access_to_view', array(
			'all'=>'Все пользователи',
			'friends'=>'Только друзья',
		),array('class'=>'form-control input-sm')); ?>
		<?php echo $form->error($model,'access_to_view'); ?>
						</div>	
						<div class="inputs">
<?php echo $form->labelEx($model,'access_to_comment',array('class'=>'col-lg-3 control-label')); ?>
		<?php echo $form->dropDownList($model, 'access_to_comment', array(
			'all'=>'Все пользователи',
			'friends'=>'Только друзья',
		),array('class'=>'form-control input-sm')); ?>
		<?php echo $form->error($model,'access_to_comment'); ?>
						</div>	

						<div class="inputs">
<?php echo $form->labelEx($model,'censor',array('class'=>'col-lg-3 control-label', 'label'=>'')); ?>
<?php echo $form->checkBox($model, 'censor',array('id'=>'censor', 'disabled'=>!$model->isNewRecord)); ?> <label for="censor">Материалы для взрослых</label>
		<?php echo $form->error($model,'censor'); ?>
						</div>	
		<?php /*if (!$model->isNewRecord) $this->widget('bootstrap.widgets.TbButton', array(
    'type'=>'danger',
    'buttonType'=>'link',
    'label'=>'Удалить альбом',
    'url'=>array('settings/remove'),
    'icon'=>'remove',
    //'block'=>true,
));*/ ?>

						<div class="inputs">
							<input type="submit" value="Сохранить" class="btn standart" /> <span id="loading_stat" style="display:none;"><i class="fa fa-cog fa-spin" style="margin-top:6px;font-size:20px;color:#246C9E;"></i></span>
						</div>

<?php $this->endWidget(); ?>

apps/love/mobile/views/photos/_comments.php
		<div style="margin-top:10px;">
<?php if(Yii::app()->user->id==$photo->user_id && $photo->album_id==0):?>
<?php if($photo->approve):?>
		    <div class="" style="margin-bottom:10px;color:#247738;">Фото одобрено модератором <i class="fa fa-check"></i> </div>
<?php else:?>
		    <div class="" style="margin-bottom:10px;color:#B25900;">Фото еще не проверено модератором <i class="fa fa-clock-o"></i> </div>
<?php endif;?>
<?php endif;?>

		
</div>

<div class="photo-like"><a href="1">Мне нравится</a> <a href="<?php echo CHtml::normalizeUrl(array('photos/like', 'id'=>$photo->id)); ?>"><i class="fa fa-heart"></i><?php echo $photo->likes; ?></a></div>

<div class="photo-like">Добавлена: <?php echo Html::date($photo->date); ?></div>

                        <div class="menu-wall menu-photoShow clearfix">
                            <ul>
			    <li>Альбом:
							<br>
<?php
	echo CHtml::link(
		$photo->album->name ? $photo->album->name : 'Фотографии со страницы', 
		CHtml::normalizeUrl(array('photos/index', 'userId'=>$photo->user_id, 'albumId'=>$photo->album_id))
	);
?></li>
							<li>Отправитель:
							<br>
<?php
	echo CHtml::link(
		$photo->user->name, 
		$photo->user->url
	);
?> 
							</li>
                            </ul>
			    
			    
		<?php $this->widget('zii.widgets.CMenu',array(
			//'type'=>'list',
			'htmlOptions'=>array('class'=>'friend-nav'),
			'encodeLabel'=>false,
			'hideEmptyItems'=>false,
			'firstItemCssClass'=>'first',
			'lastItemCssClass'=>'last',
			'items'=>array(
				array('label'=>'<i class="fa fa-exclamation-triangle"></i>Пожаловаться', 'url'=>array('photos/abuse', 'id'=>$photo->id), 'visible'=>Yii::app()->user->id!=$photo->user_id),
				array('label'=>'<i class="fa fa-mail-reply-all"></i>Сделать аватаркой', 'url'=>'#', 'visible'=>Yii::app()->user->id==$photo->user_id && $photo->album_id==0, 'linkOptions'=>array('onclick'=>'photoShow.setAvatar("'.CHtml::normalizeUrl(array('photos/index', 'setAvatar'=>$photo->id)).'"); return false;'), 'itemOptions'=>['id'=>'setava']),
				array('label'=>'<i class="fa fa-edit"></i>Редактировать', 'url'=>array('photos/editPhoto', 'id'=>$photo->id), 'visible'=>Yii::app()->user->id==$photo->user_id && $photo->album_id!=0, 'linkOptions'=>array('id'=>'editPhoto')),
				array('label'=>'<i class="fa fa-times"></i>Удалить', 'url'=>'#', 'visible'=>Yii::app()->user->id==$photo->user_id, 'linkOptions'=>array('onclick'=>'photoShow.remove("'.CHtml::normalizeUrl(array('photos/index', 'delPhoto'=>$photo->id)).'"); return false;')),
				array('label'=>'<i class="fa fa-upload"></i>Загрузить оригинал на устройство', 'url'=>'#', 'linkOptions'=>array('onclick'=>'window.open("'.$photo->imageSource.'", "_blank"); return false;')),

			),
		)); ?>
                        </div>
			
                    <div class="title row">
                        <div class="col-xs-12 col-md-12">
                            <h3 class="pull-left">Комментарии</h3>
                        </div>    
  
                    </div>
		    
<div class="recording-wall b-notice" id="commentsRows">
<?php echo $this->getComments($photo->id);?>
</div>

<?php if (Yii::app()->user->id==$photo->user_id OR Yii::app()->user->model->isReal):?>

<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'commentsForm',
    'htmlOptions'=>array('class'=>'form-horizontal comment-form'),
    'enableClientValidation'=>false,
    'enableAjaxValidation'=>false,
    'action'=>CHtml::normalizeUrl(array('photos/addComment', 'photoId'=>$photo->id))
)); ?>


					<div class="">
<?php echo $form->textArea($commentsForm,'message',array('class'=>'form-control')); ?>
<?php echo $form->error($commentsForm,'message',array('class'=>'err')); ?>


						<div class="foot">
								<div id="errorSummary" class="alert alert-danger left" style="display:none; padding:4px;">
		</div>
							<input type="submit" value="ОТПРАВИТЬ" class="btn btn-primary btn-block btn-lg" onclick="photoComments.add($('#commentsForm')); return false;" />
							<span id="loading_add_comment" class="right" style="display:none;"><img src='<?=Html::imageUrl('loading.gif')?>' align='absmiddle' /></span>
						</div>	
					</div>	


<?php $this->endWidget(); ?>



<?php elseif (Yii::app()->user->id!=$photo->user_id && !Yii::app()->user->isGuest):?>
					<div class="write-msg" style="background: #F3F9FC; padding:12px;">
						Писать комментарии могут только Реальные пользователи сайта. <a href="<?=CHtml::normalizeUrl(array('activation/index')); ?>"><b>Подтвердить реальность</b></a>
					</div>
<?php else:?>
					<div class="write-msg" style="background: #F3F9FC;">
						Пожалуйста, <a href="<?php echo CHtml::normalizeUrl(array('user/login')); ?>"><b>войдите</b></a> на сайт или <a href="<?php echo CHtml::normalizeUrl(array('user/register')); ?>"><b>зарегистрируйтесь</b></a>, чтобы написать комментарий к фотографии.
					</div>
<?php endif;?>

apps/love/mobile/views/photos/_editPhotosRows.php
		<?php foreach($photos as $row): ?>
<div class="photo_edit clearfix" id="i<?=$row->id?>">


    <div style="float:left; width:140px;">
<a href="<?=$row->normalizeUrl; ?>" id="showModalPhotoBox"><img src="<?php echo ImageHelper::thumb(140, 105, $row->user_id, $row->filename, array('method' => 'adaptiveResize'));?>" width="140" height="105" border="0" /></a>
		

    </div>
    <div style="float:left; margin-left:10px; width:565px;">
<?php if ($row->album_id):?>
	<div class="pe_title">Описание</div>
<?=CHtml::textArea('Photos[descr]', '', array('onblur'=>'editPhoto.save("'.$row->id.'");', 'id'=>'descr_'.$row->id));?>
<?php endif;?>
<a href="#" class="right" onclick="editPhoto.del('<?=CHtml::normalizeUrl(array('photos/index', 'delPhoto'=>$row->id)); ?>'); return false;"><i class="fa fa-times"></i></div>
    </div>
    

</div>
		
		

		<?php endforeach; ?>