apps/love/mobile/controllers/PayController.php
<?php

class PayController extends MobileController
{
	public function accessRules()
	{
		return array(
			array('deny',
			      //'actions'=>array('index'),
			      'users'=>array('?'),
			),
		);
	}
	
	public function actionIndex()
	{
		$kassaForm=new KassaForm;
		
		if (Yii::app()->request->isPostRequest)
		{
			$kassaForm->attributes=$_POST['KassaForm'];
			if($kassaForm->validate())
			{
				
				//$this->render('step2',array('kassaForm'=>$kassaForm));
				
				$step='2';
				$sum_array=array(
		'1'=>'10',
		'5'=>'50',
		'10'=>'100',
		'20'=>'200',
		'30'=>'300',
		'50'=>'500',
		'100'=>'1000',
						 );
				
				
				$kassa=new Kassa;
				$kassa->user_id=Yii::app()->user->id;
				$kassa->coins=$kassaForm->amount;
				$kassa->sum=$sum_array[$kassaForm->amount];
				$kassa->pay_status=0;
				$kassa->date=time();
				$kassa->save();
				
				
// Исходные данные
$shop_id = '11824';		// ID-магазинаы
$pass = '712cf92d6fe26aa10da8e0547de95863';			// Пароль магазина
$secret = 'c814dd85265b778fe3fc122c1b2e3202';		// Секретный ключ
$order = $kassa->id;		// Номер счета
$currency = 'RUR';		// RUR, USD, EUR, UAH
$sum = $sum_array[$kassaForm->amount];			// Сумма счета
$prop = array(
	      Yii::app()->user->model->name,
	      Yii::app()->user->auth->email,
	      $kassaForm->phone
	      );	// Доп свойства

// Подготовка пакета $xml
$xml = "
<request>
	<order>$order</order>
	<shop>$shop_id</shop>
	<pass>$pass</pass>
	<sum>$sum</sum>
	<currency>$currency</currency>
	<property>
		<p0>$prop[0]</p0>
		<p1>$prop[1]</p1>
		<p2>$prop[2]</p2>
		<p3>$prop[3]</p3>
		<p4>$prop[4]</p4>
		<p5>$prop[5]</p5>
		<p6>$prop[6]</p6>
		<p7>$prop[7]</p7>
		<p8>$prop[8]</p8>
		<p9>$prop[9]</p9>
	</property>
</request>";
//echo $xml;
// Кодирование пакета $xml методом base64_encod
$xml_encoded = base64_encode($xml);
// Создание подписи
$lqsignature = base64_encode(sha1($secret.$xml_encoded.$secret,1));
				
				
				
				
				/*$result = Yii::app()->CURL->run('http://www.free-kassa.ru/merchant/cash.php', TRUE, array(
					'm' => 2581,
					'oa' => $kassaForm->amount,
				));*/
				
				/*$kassa=new Kassa;
				$kassa->user_id=Yii::app()->user->id;
				$kassa->amount=$kassaForm->amount;
				$kassa->pay_status=0;
				$kassa->date=date("Y-m-d H:i:s");
				$kassa->save();
				
				$secret_word='fgdhdghgjju65y5hgdd';
				$merchant_id=2581;
				$order_id=$kassa->id;
				
				header('Location: http://www.free-kassa.ru/merchant/cash.php?m='.$merchant_id.'&oa='.$kassaForm->amount.'&s='.md5($merchant_id.":".$kassaForm->amount.":".$secret_word.":".$order_id).'&o='.$order_id);
				
				*/
				
				
				$balance=$kassaForm->amount;
				
				
				//$user=Users::model()->findByPk(Yii::app()->user->id);
				
				//Yii::app()->user->model->saveAttributes(array('balance'=>new CDbExpression('`balance`+'.$balance)));
				
					//Yii::app()->user->setFlash('success','Баланс пополнен.');
					//$this->refresh();

			}	
		}
		
		if ($step=='2') {

		
		}
		$this->render('kassa',array('kassaForm'=>$kassaForm, 'step'=>$step, 'xml_encoded'=>$xml_encoded, 'lqsignature'=>$lqsignature));
	}
	
	public function actionSuccess()
	{
		$this->render('success');
	}
	
	public function actionFail()
	{
		$this->render('fail');
	}
	
	public function actionHistory()
	{
		$history=Transaction::model()->findAll(array('condition'=>'user_id='.Yii::app()->user->id, 'order'=>'id DESC'));
		$this->render('history',array('history'=>$history));
	}
}

apps/love/mobile/views/pay/_menu.php
<div class="mytabs" style="margin-top:-15px;">
<?php $this->widget('Menu', array(
	'htmlOptions'=>array('class'=>'nav nav-tabs nav-friends'),
    'encodeLabel'=>false,
			'items'=>array(
				array('label'=>'Пополнение баланса', 'url'=>array('pay/index'), 'linkOptions'=>array()),
				array('label'=>'История операций', 'url'=>array('pay/history'), 'linkOptions'=>array()),
			),
)); ?>
</div>

apps/love/mobile/views/pay/fail.php
<?php
//$this->pageTitle =Yii::t(Yii::app()->language, 'Пополнение баланса');
$this->breadcrumbs=array(
	//Yii::t(Yii::app()->language, 'Пополнение баланса')
);
?>


			<div class="title">
				<h3 class="left"><?php echo Yii::t(Yii::app()->language, 'Информация');?></h3>
			</div>	
			<div class="section-tabs">


				<div class="tab visible">

Платеж отменен. <?php echo CHtml::link('Вернуться назад.',array('pay/index')); ?>


			</div>	
		</div>

apps/love/mobile/views/pay/history.php
<?php
$this->pageTitle =Yii::t(Yii::app()->language, 'История операций');
$this->breadcrumbs=array(
	Yii::t(Yii::app()->language, 'История операций')
);
?>
            <div class="title row">
                <div class="col-md-12 col-xs-12">
                    <h3 class="pull-left">История операций</h3>
                </div>   
            </div>

			<div class="section-tabs">
<?php $this->renderPartial('_menu'); ?>

				<div class="tab visible">
<table class="table table-striped table-hover" cellspacing="1" cellpadding="0"> 
<thead>
  <tr>
    <th>Дата оплаты</th>
    <th>Сумма</th>
    <th>Операция</th>

  </tr>
</thead>

<tbody>
		<?php foreach($history as $row): ?>
		

  <tr class="light">
    <td><?=Html::date($row->date);?></td>
    <td><?=Yii::t('app','{n} монета|{n} монеты|{n} монет', $row->coins);?></td>
    <td><?=$row->comment_payment;?></td>

  </tr>
		
		<?php endforeach; ?>
</tbody>
</table>

			</div>	
		</div>

apps/love/mobile/views/pay/index.php
<?php
$this->pageTitle =Yii::t(Yii::app()->language, 'Пополнение баланса');
$this->breadcrumbs=array(
	Yii::t(Yii::app()->language, 'Пополнение баланса')
);
?>
			<div class="title">
				<h3 class="left"><?php echo Yii::t(Yii::app()->language, 'Пополнение баланса');?></h3>
			</div>	
			<div class="section-tabs">
<?php //$this->renderPartial('_menu'); ?>

				<div class="tab visible">




<div class="r">

<?php if(!$ok): ?>

<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'codeForm',
    'htmlOptions'=>array('class'=>'reg-sms'),
    'action'=>CHtml::normalizeUrl(array('transaction/index')),

)); ?>

	<ul id="errorSummary" style="display:none;color:red;">
		</ul>
				<div class="activation">
					<div class="col1">	
						<div style="font-size:14px;margin-bottom:8px;">
							
Чтобы пополнить баланс
						</div>
						
						<div class="inputs" style="margin-bottom:8px;">
							<?php echo $form->labelEx($SMSForm,'country', array('label'=>'Выберите страну')); ?>
							<?php echo $form->dropDownList($SMSForm,'country',$SMSForm->countries, array('class'=>'txt-field')); ?>
							
							<?php echo $form->error($SMSForm,'country',array('style'=>'margin-left:105px;color:red; margin-bottom:5px;')); ?>

						</div>
						
						<div style="font-size:14px;margin-bottom:8px;">
							
Отправьте <span style="color:#CD1B62;">SMS c  текстом <?=$SMSForm->tagPrefix('big');?></span> на короткий <span style="color:#CD1B62;">номер <?=$SMSForm->tagNumber('big');?></span>
						</div>
						
						<div class="inputs" style="margin-bottom:8px;">
							<?php echo $form->labelEx($SMSForm,'code', array('label'=>'Введите код который вам пришел на телефон')); ?>
							<?php echo $form->textField($SMSForm,'code',array('class'=>'txt-field')); ?>
							
							<?php echo $form->error($SMSForm,'code',array('style'=>'margin-left:105px;color:red; margin-bottom:5px;')); ?>

						</div>

						<div class="inputs">
							<input type="submit" value="Пополнить" class="button in-block" />
						</div>	
					</div>	

				</div>	

				
<?php $this->endWidget(); ?>

<?php else: ?>
Ваш счет успешно пополнен. <?php echo CHtml::link('Вернуться назад.',array('transaction/index')); ?>

<?php endif; ?>


</div>


			</div>	
		</div>

apps/love/mobile/views/pay/kassa.php
<?php
$this->pageTitle =Yii::t(Yii::app()->language, 'Пополнение баланса');
$this->breadcrumbs=array(
	Yii::t(Yii::app()->language, 'Пополнение баланса')
);
?>
            <div class="title row">
                <div class="col-md-12 col-xs-12">
                    <h3 class="pull-left">Пополнение баланса</h3>
                </div>   
            </div>

			<div class="section-tabs">
<?php $this->renderPartial('_menu'); ?>


				<div class="tab visible">
<?php if(Yii::app()->request->isPostRequest && $kassaForm->validate()): ?>
<script type="text/javascript">
var timetogo = 2;
var timer = window.setInterval(function()
{
    var str = timetogo;
    $('#counter').text(str);
    
    if (timetogo <= 0)
    {
        $("#goKassa").submit();
         window.clearInterval(timer);
    }
    timetogo--;
}, 1000);
</script> 
<style>
        .vc_text {margin: 10px 0px 10px 0px;font-weight:bold;font-size:11px;}
</style>
<form action="http://businesskassa.com/POST.php" method="post" id="goKassa">
	<input type="hidden" name="xml_encoded" value="<?= $xml_encoded; ?>" />
	<input type="hidden" name="lqsignature" value="<?= $lqsignature; ?>" />
	<input type="submit" class="btn btn-primary btn-lg" value="Оплатить в BusinessKass" style="width:200px;" />
	
	<div class="vc_text">Перенаправление на страницу оплаты через <span id="counter">3</span> сек.</div>
</form>
<div class="vc_text">
<img src="<?php echo Html::imageUrl('pays/sber.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/termin.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/visa.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/abank.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/bank.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/euro.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/liqpay.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/mastercard.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/p24.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/paypal.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/pm.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/svyz.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/w1.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/ya.png');?>" alt="" align="absmiddle" width="24">
<img src="<?php echo Html::imageUrl('pays/zp.png');?>" alt="" align="absmiddle" width="24">
</div>
<?php else: ?>


<div class="r">

<?php $form = $this->beginWidget('CActiveForm', array(
    'htmlOptions'=>array('class'=>'reg-form'),
)); ?>


<div style="margin-bottom:10px;">Cейчас у Вас на счету: <?=Yii::t('app','{n} монета|{n} монеты|{n} монет', Yii::app()->user->balance)?></div>


    	<?php echo $form->radioButtonList($kassaForm,'amount', array(
		//'1'=>'+1 монета',
		'5'=>'+5 монет',
		'10'=>'+10 монет',
		'20'=>'+20 монет',
		'30'=>'+30 монет',
		'50'=>'+50 монет',
		'100'=>'+100 монет',
		)); ?><br/>


	<?php echo $form->error($kassaForm,'amount',array('style'=>'color:red;')); ?>
	
<?php /*echo $form->labelEx($kassaForm,'phone',array('class'=>'col-lg-3 control-label')); ?>

		<?php echo $form->textField($kassaForm, 'phone',array('class'=>'txt-field')); ?>
		<?php echo $form->error($kassaForm,'phone');*/ ?>
	
<div class="form-group">
					<input type="submit" value="Продолжить" class="btn btn-primary btn-lg" style="width:100px;"/> <span id="loading_stat" style="display:none;"><img src='<?=Html::imageUrl('loading.gif')?>' align='absmiddle' /></span>
				</div>	
<?php $this->endWidget(); ?>




</div>
<?php endif; ?>


			</div>	
		</div>

apps/love/mobile/views/pay/success.php
			<div class="title">
				<h3 class="left"><?php echo Yii::t(Yii::app()->language, 'Информация');?></h3>
			</div>	
			<div class="section-tabs">


				<div class="tab visible">

Баланс пополнен. <?php echo CHtml::link('Перейти на мою страницу.',array('site/index')); ?>


			</div>	
		</div>