apps/love/mobile/controllers/MessagesController.php
<?php

class MessagesController extends MobileController
{
	public $layout='col_main';
	
	public function accessRules()
	{
		return array(
			array('deny',
			      'actions'=>array('index', 'dialogue'),
			      'roles'=>array('guest'),
			),
		);
	}
	
	public function actionIndex()
	{
		if (Yii::app()->request->isPostRequest && is_array($_POST['to_message']))
		{
			foreach($_POST['to_message'] as $item) {
				Messages::model()->deleteByPk($item, 'from_userId='.Yii::app()->user->id);
			}
			
			if (Yii::app()->request->isAjaxRequest) {
				echo CJSON::encode(array());
				return;
			}
		}
		
		$criteria=new CDbCriteria(array(
			'condition'=>'`t`.`from_userId`=:user_id AND `t`.`folder`=:folder',
			'params'=>array(':user_id'=>Yii::app()->user->id, ':folder'=>$_GET['folder']=='outbox' ? 'outbox' : 'inbox'),
			'with'=>array('user'=>array()),
			'order'=>'t.time DESC',
				
		));
		
		$count = Messages::model()->count($criteria);
		$pages = new CPagination($count);
		$pages->pageSize=Yii::app()->params['messages_limit'];
		$pages->applyLimit($criteria);
		
		$messages=Messages::model()->findAll($criteria);
		
		if (Yii::app()->request->isAjaxRequest && $_GET['_a']=='container_mail') {
			$this->render('_index', array('messages'=>$messages, 'pages'=>$pages, 'count'=>$count));
		} else {
			$this->render('index', array('messages'=>$messages, 'pages'=>$pages, 'count'=>$count));
		}
	}
	
	public function actionDialogue()
	{
		if (Yii::app()->request->isPostRequest && is_array($_POST['to_message']))
		{
			foreach($_POST['to_message'] as $item) {
				Messages::model()->deleteByPk($item, 'from_userId='.Yii::app()->user->id);
			}
			
			if (Yii::app()->request->isAjaxRequest) {
				echo CJSON::encode(array());
				return;
			}
		}
		
		$user=User::model()->findByPk($_GET['id']);
		
		if($user===null)
			throw new CHttpException(404,'Contact not found.');
		
		if($user->id==Yii::app()->user->id)
			throw new CHttpException(404,'It is impossible to write a message.');
		
		
		$model=new Messages;
		
		if(Yii::app()->request->isPostRequest && !Yii::app()->user->isGuest)
		{
			$model->attributes=$_POST['Messages'];
			if($model->validate())
			{
				$model->from_userId = $user->id;
				$model->to_userId = Yii::app()->user->id;
				$model->unread = 1;
				$model->folder = 'inbox';
				$model->time = time();
				
				if ($model->save(false))
				{
					$model=new Messages;
					$model->attributes=$_POST['Messages'];
					$model->from_userId = Yii::app()->user->id;
					$model->to_userId = $user->id;
					$model->folder = 'outbox';
					$model->unread = 0;
					$model->time = time();
					if ($model->save())
					{
						if (Yii::app()->request->isAjaxRequest)
						{
							echo CJSON::encode(array('html'=>$this->getDialogue($_GET['id'])));
							return;
						}
						Yii::app()->user->setFlash('sent','to');
						$this->refresh();
					}
				}
			}
			elseif (Yii::app()->request->isAjaxRequest)
			{
				echo CActiveForm::validate($model);
				Yii::app()->end();
			}
		}
		
		if (Yii::app()->request->isAjaxRequest && $_GET['_a']=='container_mail') {
			echo $this->getDialogue($user->id);
		} else {
			$this->render('dialogue', array('user'=>$user, 'model'=>$model));
		}
	}
	
	public function getDialogue($id)
	{
		$criteria=new CDbCriteria(array(
			'condition'=>'`t`.`from_userId`=:user_id AND `t`.`to_userId`=:to_userId',
			'params'=>array(':user_id'=>Yii::app()->user->id, ':to_userId'=>$id),
			'with'=>array('user'=>array()),
			'order'=>'t.time DESC',
				
		));
		
		$count = Messages::model()->count($criteria);
		$pages = new CPagination($count);
		$pages->pageSize=Yii::app()->params['messages_limit'];
		$pages->applyLimit($criteria);
		
		$messages=Messages::model()->findAll($criteria);
		
		foreach($messages as $row) {
			if ($row->unread)
				$row->saveAttributes(array('unread'=>0));
		}

		return $this->renderPartial('_dialogue', array(
			'messages'=>$messages,
			'pages'=>$pages,
			'count'=>$count)
		, true);
	}
	
	public function actionSend()
	{
		$user=User::model()->findByPk($_GET['id']);
		
		if($user===null)
			throw new CHttpException(404,'Contact not found.');
		
		if($user->id==Yii::app()->user->id)
			throw new CHttpException(404,'It is impossible to write a message.');
		
		$model=new Messages;
		
		if(Yii::app()->request->isPostRequest && !Yii::app()->user->isGuest)
		{
			$model->attributes=$_POST['Messages'];
			if($model->validate())
			{
				
				$model->from_userId = $user->id;
				$model->to_userId = Yii::app()->user->id;
				$model->unread = 1;
				$model->folder = 'inbox';
				$model->time = time();
				
				if ($model->save(false))
				{
					$model=new Messages;
					$model->attributes=$_POST['Messages'];
					$model->from_userId = Yii::app()->user->id;
					$model->to_userId = $user->id;
					$model->folder = 'outbox';
					$model->unread = 0;
					$model->time = time();
					if ($model->save())
					{
						if (Yii::app()->request->isAjaxRequest)
						{
							echo CJSON::encode(array('ok'=>1));
							Yii::app()->end();
						}
						Yii::app()->user->setFlash('sent','to');
						$this->refresh();
					}
				}
			}
			elseif (Yii::app()->request->isAjaxRequest)
			{
				echo CActiveForm::validate($model);
				Yii::app()->end();
			}
		}
		
		$this->render('send', array('model'=>$model, 'user'=>$user));
	}
}

apps/love/mobile/controllers/SearchController.php
<?php

class SearchController extends MobileController
{
	public $layout='col_main';
	
	public $searchEngine='Sphinx';
	//public $searchEngine='Mysql';


	public function accessRules()
	{
		return array(
			array('deny',
			      'roles'=>array('guest'),
			),
		);
	}
	
	public function init()
	{
		parent::init();
		
		if (!Yii::app()->user->model->isReal && is_array($_GET['c'])) {
			$this->redirect(array('activation/index'));
			Yii::app()->end();
		}
		
		if ($_GET['c']) {
			$cookie = new CHttpCookie('searchCriteria', serialize($_GET['c']));
			$cookie->expire = time()+60*60*24*180;
			Yii::app()->request->cookies['searchCriteria'] = $cookie;
		}
		if ($cookie = Yii::app()->request->cookies['searchCriteria']) {
			$_GET['c']=unserialize($cookie->value);
		}
	}

	public function actionIndex()
	{
		if (Yii::app()->user->model->isReal) {
			if (Yii::app()->request->isAjaxRequest && $_GET['_a']=='getQuickSearch') {
				echo $this->getQuickSearch();
				return;	
			}
			$this->render('index');
		} else {
			$criteria=new CDbCriteria(array(
			'condition'=>'`t`.`isBot`=1 AND photo.approve=1',
			//'params'=>array(':user_id'=>$this->profile->id),
				'with'=>array(
					'profile'=>array(),
					//'position'=>array(),
					'country',
					'region',
					'city',
					'photo'
				),
				'order'=>'rand()',
				'limit'=>Yii::app()->params['mainRandomUsers_limit'],
				
			));
			$profiles=User::model()->findAll($criteria);
			$this->render('index2', array('profiles'=>$profiles));
		}
	}
	
	public function actionExtended()
	{

		
		$this->render('extended');
	}
	
	public function getQuickSearch()
	{
		return $this->{getQuickSearch.Yii::app()->params['searchEngine']}();
	}
	
	public function getQuickSearchSphinx()
	{
		$searchCriteria = new stdClass();
		$pages = new CPagination();
		$pages->pageSize = Yii::app()->params['searchUsers_limit'];
		$pages->params=array();
		
		$searchCriteria->select = '*';
		
		if ($_GET['c']['country_id'])
			$searchCriteria->filters['country_id'] = intval($_GET['c']['country_id']);
			
		if ($_GET['c']['country_id'] && $_GET['c']['region_id'])
			$searchCriteria->filters['region_id'] = intval($_GET['c']['region_id']);
			
		if ($_GET['c']['country_id'] && $_GET['c']['region_id'] && $_GET['c']['city_id'])
			$searchCriteria->filters['city_id'] = intval($_GET['c']['city_id']);
			
		if ($_GET['c']['sex'])
			$searchCriteria->filters['sex'] = intval($_GET['c']['sex']);
			
		if (is_numeric($_GET['c']['age_from']) OR is_numeric($_GET['c']['age_to']))
			$searchCriteria->filtersRange['age'] = array(intval($_GET['c']['age_from']), intval($_GET['c']['age_to'] ? $_GET['c']['age_to'] : 80));
		
		if ($_GET['c']['new'])
			$searchCriteria->filtersRange['reg_date'] = array(time() - 60*60*24, time());
			
		if ($_GET['c']['photo'])
			$searchCriteria->filters['have_photo'] = 1;
			
		if ($_GET['c']['real'])
			$searchCriteria->filters['isReal'] = 1;
			
		if ($_GET['c']['tg']) {
			
			foreach($_GET['c']['tg'] as $target) {
				//$searchCriteria->setFilterRange('target')=intval($target);
				$searchCriteria->query.=' @target '.intval($target).'*';
			}
		}	
		/*if ($_GET['tg']=='3')
		{
			$searchCriteria->query.=' @target 1';
			//$searchCriteria->query.=' @target 2';
		}
			
		if ($_GET['tg']=='2')
		{
			$searchCriteria->query.=' @target 12';
		}*/
			
			
		//if ($_GET['q'])
		//	$searchCriteria->query = htmlspecialchars(substr($_GET['q'],0,100));
			
		$searchCriteria->paginator = $pages;
		$searchCriteria->orders = 'position DESC';
		
		if ($_GET['c']['online'])
			$searchCriteria->from = 'usersonline';
		else
			$searchCriteria->from = 'users';
		
		$result = Yii::app()->sphinx->searchRaw($searchCriteria);
		
		//print_r($result);
		
		if ($result['matches'])
		{
			$ids = array_keys($result['matches']);
			//print_r($result['matches']);
			//print_r($ids);
			//Yii::log(CVarDumper::dump($result['matches'], 10,true));
			//Yii::log(print_r($result, true));
			
			$count=$result['total_found'];
			$criteria=new CDbCriteria;
			//$criteria->select='id, img, last_date, login, sex, count_photo, count_friends, rating';
			$criteria->with=array(
				'profile'=>array(
					//'select'=>'birthday, name, lastname, orientation',
					'with'=>array(),
				),
				'country',
				'region',
				'city'
			);
			$criteria->addInCondition('id',$ids);
			$criteria->order='FIELD(id, '.implode(',', $ids).')';
			$profiles=User::model()->findAll($criteria);
		}
		else {
			$profiles=array();
			$pages=null;
			$count=0;
		}
		
		return $this->renderPartial('_rows', array('profiles'=>$profiles, 'pages'=>$pages, 'count'=>$count), true);
	}
	
	public function getQuickSearchMysql()
	{
		Yii::beginProfile('Search result');
		//Yii::log('Search engine: ');
		$criteria=new CDbCriteria(array(
			//'condition'=>'`t`.`user_id`=:user_id',
			//'params'=>array(':user_id'=>$this->profile->id),
			'with'=>array(
				'profile'=>array(),
				'position'=>array(),
			),
			'order'=>'position.time DESC',
				
		));
		
		if ($_GET['c']['sex'])
			$criteria->addCondition('`t`.`sex`='.intval($_GET['c']['sex']));
		
		if ($_GET['c']['age_from']) {
			$criteria->addCondition("`t`.`birthday`<'".date("Y-m-d", mktime(0, 0, 0, date("m"), date("d"), date("Y")-$_GET['c']['age_from']))."' AND `birthday`>'0000-12-31'");
		}
		
		if ($_GET['c']['age_to']) {
			$criteria->addCondition("`t`.`birthday`>'".date("Y-m-d", mktime(0, 0, 0, date("m"), date("d"), date("Y")-$_GET['c']['age_to']-1))."'");
		}
		
		if ($_GET['c']['country_id'])
			$criteria->addCondition('`t`.`country_id`='.intval($_GET['c']['country_id']));
		
		if ($_GET['c']['region_id'] && $_GET['c']['region_id'])
			$criteria->addCondition('`t`.`region_id`='.intval($_GET['c']['region_id']));
		
		if ($_GET['c']['country_id'] && $_GET['c']['region_id'] && $_GET['c']['city_id'])
			$criteria->addCondition('`t`.`city_id`='.intval($_GET['c']['city_id']));
		
		//$criteria->addInCondition("`profile`.`target`", array('1'));
		
		//$criteria->addSearchCondition('`profile`.`target`', '13', true, 'OR');
		//$criteria->addSearchCondition('`profile`.`target`', '7', true, 'OR');
		
		
		if ($_GET['tg']=='2')
		{
			$criteria2=new CDbCriteria;
			$criteria2->addSearchCondition('`profile`.`target`', '12', true, 'OR');
			$criteria->mergeWith($criteria2);
		}
		elseif ($_GET['tg']=='3')
		{
			$criteria2=new CDbCriteria;
			$criteria2->addSearchCondition('`profile`.`target`', '1', true, 'OR');
			$criteria2->addSearchCondition('`profile`.`target`', '2', true, 'OR');
			$criteria2->addSearchCondition('`profile`.`target`', '9', true, 'OR');
			$criteria2->addSearchCondition('`profile`.`target`', '10', true, 'OR');
			$criteria->mergeWith($criteria2);
		}
		
		
		$count = User::model()->count($criteria);
		$pages = new CPagination($count);
		$pages->pageSize=Yii::app()->params['searchUsers_limit'];
		$pages->applyLimit($criteria);
		
		$profiles=User::model()->findAll($criteria);
		
		Yii::endProfile('Search result');
		return $this->renderPartial('_rows', array('profiles'=>$profiles, 'pages'=>$pages, 'count'=>$count, 'setNum'=>6), true);
	}
}

apps/love/mobile/controllers/UserController.php
<?php

class UserController extends MobileController
{
	public $layout = 'col_main';
	

	
	public function actions()
	{
		return array(
                    //  captcha.
                     'captcha'=>array(
                        'class'=>'CaptchaAction',
                        'maxLength'=> 3,
                        'minLength'=> 4,
                        'testLimit'=> 1,
                    )
                );
	}
	
	public function actionIndex()
	{
		$this->actionLogin();
	}
	
	public function actionRegister()
	{
		if (!Yii::app()->user->isGuest)
			$this->redirect(Yii::app()->user->returnUrl);
			
		$user=new User;
		$user->setScenario('register');
		$this->performAjaxValidation($user);
		if(Yii::app()->request->isPostRequest)
		{
			$user->attributes=$_POST['User'];
			if($user->validate())
			{
				Yii::app()->vc->processStatField(array('reg'=>1));
				$user->subaccount_id=Yii::app()->vc->subaccountId;
				if ($user->save(false))
				{
					$auth=new LoginForm;
					$auth->username=$_POST['User']['email'];
					$auth->password=$_POST['User']['password'];
					$auth->rememberMe=true;
					$auth->login();
					$this->redirect(array('site/index'));
				}
			}
		}
		$this->render('register', array('model'=>$user));
	}
	
	public function actionLostpassword()
	{
		if (!Yii::app()->user->isGuest)
			$this->redirect(Yii::app()->user->returnUrl);
			
		$model=new LostpasswordForm;
		$user=false;
		if(Yii::app()->request->isPostRequest)
		{
			$model->attributes=$_POST['LostpasswordForm'];
			if($model->validate())
			{
				$userAuth = UserAuthorization::model()->find('email=:email', array(':email'=>$model->attributes['email']));
				$user = User::model()->findByPk($userAuth->user_id);
				if ($user->id)
				{
					$mail=Yii::app()->Smtpmail;
					$mail->CharSet='utf-8';
					$mail->SetFrom($mail->Username, Yii::app()->request->domain);
					$mail->Subject    = 'Восстановление пароля к '.Yii::app()->request->domain;
					$mail->MsgHTML($this->render('/email/lostpassword', array('email'=>$userAuth->email, 'password'=>$userAuth->password, 'name'=>$user->name), true));
					$mail->AddAddress($userAuth->email, "");
					if(!$mail->Send()) {
						throw new CHttpException(500,'Mailer Error.');
						//$model->addError('email', 'Mailer Error: ' . $mail->ErrorInfo);
					}else {
						Yii::app()->user->setFlash('sentemail',$userAuth->email);
						$this->refresh();
					}
				}
				else
					$model->addError('email', 'A user with this email was not found');
			}
		}
		
		$this->render('lostpassword', array('model'=>$model, 'user'=>$user));
	}
	
	public function actionLogin()
	{
		if (!Yii::app()->user->isGuest)
			$this->redirect(Yii::app()->user->returnUrl);
			
		if (isset($_GET['auto']))
		{
			$auto=explode(";", base64_decode($_GET['auto']));
			$auth=new LoginForm;
			$auth->username=$auto['0'];
			$auth->password=$auto['1'];
			$auth->rememberMe=true;
			$auth->login();
			$this->redirect(array('site/index'));
			Yii::app()->end();
		}
			
		$model=new LoginForm;
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			
			if($model->validate() && $model->login())
			{
				$this->redirect(array('site/index'));
			}
		}
		
		$this->render('login', array('model'=>$model));
	}
	
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='registerForm')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

apps/love/mobile/views/messages/_index.php
<?php if (!$messages): ?>
<p class="text-muted text-center">Здесь будет выводиться список Ваших сообщений.

<br>
Пожалуйста, выберите <a href="<?=CHtml::normalizeUrl(array('search/index')); ?>"><b>пользователя</b></a>, чтобы начать общение.</p>


<?php else: ?>	
			
			
<div class="recording-wall b-notice" style="margin-left:0px;margin-right:0px;">


<?php foreach($messages as $index=>$row):?>
                <?php if ($index>0):?><hr style="margin-top:5px;margin-bottom:10px;"/><?php endif;?>
		
                <div class="row" id="comment_<?=$row->id?>" style="margin-right:0px;">
                    <div class="col-xs-3 col-sm-2 col-md-2 text-left" style="width:80px;">
<a href="<?=CHtml::normalizeUrl(array('messages/dialogue', 'id'=>$row->user->id)); ?>"><img src="<?php echo $row->user->getImage(55,55, 'camera_s.png');?>" /></a>
                    </div>
                    <div class="col-xs-8 col-sm-10 col-md-10">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="notice-text">
                                    <div class="head">
						<a href="<?=CHtml::normalizeUrl(array('messages/dialogue', 'id'=>$row->user->id)); ?>"><?=$row->user->id ? $row->user->name : 'DELETED'?></a>
<?php if ($row->user->isOnline):?>
								<label class="dialogue-online"><?php if (!$row->user->isMobile):?><i class="fa fa-circle"></i><?php else:?><i class="fa fa-mobile"></i>Mobile<?php endif;?></label>
<?php endif;?>
				    </div>
				    <div class="message<?php if($row->unread) echo ' unread';?>"><a href="<?=CHtml::normalizeUrl(array('messages/dialogue', 'id'=>$row->user->id)); ?>"><?=$row->message ?></a></div>
                                    <div class="foot">
                                        <i class="fa fa-clock-o"></i>
                                         <?php echo Html::date($row->time);?>
					 
			 
                                    </div>  
                                </div> 
                            </div>     
                        </div>
                    </div>
                </div> 

<?php endforeach;?>

</div>

<div class="text-center">
<?php $this->widget('ext.bootstrap3.widgets.BsPager', array(
        //'id'=>'wallPages',
        'pages'=>$pages,
       // 'cssFile'=>Html::cssUrl('pager.css'),
	'htmlOptions'=>array('class'=>'pagination pagination-sm'),
        //'maxButtonCount'=>5,
        'nextPageLabel'=>'<i class="fa fa-angle-right"></i>',
	'prevPageLabel'=>'<i class="fa fa-angle-left"></i>',
        'lastPageLabel'=>'<i class="fa fa-angle-double-right"></i>',
	'firstPageLabel'=>'<i class="fa fa-angle-double-left"></i>',
        ));
?>
</div>


<?php endif; ?>

apps/love/mobile/views/messages/_menu.php
<div class="mytabs" style="margin-top:-15px;">
<?php $this->widget('Menu', array(
    'htmlOptions'=>array('class'=>'nav nav-tabs'),
    'encodeLabel'=>false,
			'items'=>array(
				array('label'=>'Полученные', 'url'=>array('messages/index'), 'linkOptions'=>array()),
				array('label'=>'Отправленные', 'url'=>array('messages/index', 'folder'=>'outbox'), 'linkOptions'=>array()),
			),
)); ?>
</div>

apps/love/mobile/views/messages/dialogue.php
<?php $this->pageTitle='Диалог';?>
<?php 		$this->breadcrumbs=array(
			'Диалог',
		);
?>

            <div class="title row">
                <div class="col-md-9 col-xs-9">
                    <h3 class="pull-left"><?php echo $user->name?><?php if ($user->isOnline):?>
								<label class="dialogue-online"><?php if (!$user->isMobile):?><i class="fa fa-circle"></i><?php else:?><i class="fa fa-mobile"></i>Mobile<?php endif;?></label>
<?php endif;?></h3>
                </div>
		<div class="col-xs-3 col-md-3">
                        <a class="pull-right addphotos-link" href="<?php echo CHtml::normalizeUrl(array('messages/index')); ?>"><i class="fa fa-reply"></i></a>       
                 </div>     
            </div>

	<div class="row dialogue">

	<div >

<?php if (Yii::app()->user->model->isReal):?>
<?php if(Yii::app()->user->hasFlash('sent')): ?>
<div class="alert flash-success">
	Сообщение отправлено.
</div>
<?php endif; ?>

<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'dialogueForm',
    'htmlOptions'=>array('class'=>'dialogue-form'),
    'enableClientValidation'=>true,
    'enableAjaxValidation'=>false,
    'clientOptions'=>array(
            'validateOnSubmit'=>true,
            'validateOnType'=>false,
            'validateOnChange'=>false,
            'beforeValidate'=>'js:function(){

                return true;
             }',

            //'afterValidate'=>'js:afterValidateSettingsForm',
    ),

)); ?>
<?php echo CHtml::errorSummary($model);?>

<div id="errorSummary" class="alert alert-danger alert-form-validate" style="display:none;"></div>

<?php echo $form->textArea($model, 'message', array('class'=>'form-control')); ?>
<input type="submit" value="Отправить" class="btn btn-primary btn-lg" onclick="YCMail.add($('#dialogueForm')); return false;" style="width:150px;" />
<span id="loading_sentForm"><i class="fa fa-spinner fa-spin"></i></span>
<?php $this->endWidget(); ?>	
<?php else:?>

					<div class="noreal-alert">
						<p>Ваша анкета не активна!<br>Писать сообщения могут только активные пользователи сайта с статусом Реал.</p>
						<a href="<?=CHtml::normalizeUrl(array('activation/index')); ?>" class="btn btn-primary btn-block btn-lg">Получить Real - статус</a>
					</div>


<?php endif;?>

			
<?php if (!$user->isOnline) {
	echo '<div class="offline-dialogue-text">';
	echo  $user->name.' ';
    echo $user->sex==1 ? 'был ' : 'была ';
    echo 'в сети ';
    echo Html::date($user->last_date);
	if ($user->isMobile) {
		echo ' <i class="fa fa-mobile"></i>';
	}
    echo '</div>';
}
?>
			
			
<div id="container_mail">
<?php echo $this->getDialogue($user->id);?>
</div>


</div>
</div>

apps/love/mobile/views/messages/index.php
<?php $this->pageTitle='Мои Cообщения';?>
<?php
$this->breadcrumbs=array('Сообщения');
?>
            <div class="title row">
                <div class="col-md-12 col-xs-12">
                    <h3 class="pull-left">Мои Cообщения</h3>
                </div>  
            </div>

<?php $this->renderPartial('_menu', array()); ?>

	<div class="row dialogue" id="container_mail">
<?php $this->renderPartial('_index', array('messages'=>$messages, 'pages'=>$pages, 'count'=>$count)); ?>
		</div>

apps/love/mobile/views/messages/send.php
<?php $this->pageTitle='Написать сообщение';?>
<?php 		$this->breadcrumbs=array(
			'Написать сообщение',
		);
?>




                    <div class="title row">
                        <div class="col-xs-12 col-md-12">
                            <h3 class="pull-left">Написать сообщение</h3>
                        </div>    
  
                    </div>
		    
		    
            <div class="section-tabs row">
		    
                <div class="col-md-12 tabs-container">
                    <div class="tab-content">
<?php if(Yii::app()->user->hasFlash('sent')): ?>
<div class="alert flash-success">
	Сообщение отправлено.
</div>
<?php endif; ?>



<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'messageForm',
    'htmlOptions'=>array('class'=>'well1'),
    'enableClientValidation'=>false,
    'enableAjaxValidation'=>false,
)); ?>
	<div id="errorSummary" class="alert alert-danger" style="display:none;">
		</div>
<?php echo CHtml::errorSummary($model, '','',['class'=>'alert alert-danger']);?>


<div class="media">
<a class="pull-left" href="<?=$user->url; ?>"><img src="<?php echo $user->have_photo==1 ? ImageHelper::thumb(55, 55, $user->id, $user->photo, array('method' => 'adaptiveResize')) : Html::imageUrl('camera_s.png');?>" class="media-object" /></a>

  <div class="media-body">
    <h4 class="media-heading">Кому: <a href="<?=$user->url; ?>"><?php echo $user->name; ?></a></h4>
<?php if (Yii::app()->user->model->isReal):?>
<?php echo $form->textArea($model, 'message', array('class'=>'form-control', 'style'=>'height:120px;')); ?>

<div style="margin-top:5px; font-size:11px;">	
<input type="submit" value="ОТПРАВИТЬ" class="btn btn-primary btn-block btn-lg" onclick="sendMessage($('#messageForm')); return false;" />

		<a href="<?=CHtml::normalizeUrl(array('messages/dialogue', 'id'=>$user->id)); ?>" class="left">Перейти в диалог</a>
<?php elseif (!Yii::app()->user->isGuest):?>
				<div>
					<div class="about-service" style="background: #fff; padding:12px;">
						<p>Ваша анкета не активна! Писать сообщения могут только активные пользователи сайта с статусом Реал.</p>
						<a href="<?=CHtml::normalizeUrl(array('activation/index')); ?>"><b>Подтвердить реальность Вашей анкеты с помощью активации Реал статуса!</b></a>
					</div>
				</div>
<?php else:?>
				<div>
					<div class="about-service" style="background: #fff; padding:12px;">
						<p>Пожалуйста, <a href="<?php echo CHtml::normalizeUrl(array('user/login')); ?>"><b>войдите</b></a> на сайт или <a href="<?php echo CHtml::normalizeUrl(array('user/register')); ?>"><b>зарегистрируйтесь</b></a>, чтобы написать сообщение.</p>
					</div>
				</div>
<?php endif;?>
  </div>
</div>


<?php $this->endWidget(); ?>  </div></div>
</div>